### ISSUE TITLE
win10

### ISSUE THREAD

**Issue by lylyjy** [hijkzzz/pymarl2#11]
Hi, when I run the code in win10, it occurs that:

def recursive_dict_update(d, u):
    for k, v in u.items():

Exception has occurred: AttributeError
'NoneType' object has no attribute 'items'
  File "D:\src\main.py", line 55, in recursive_dict_update
    for k, v in u.items():
  File "D:\src\main.py", line 95, in <module>
    config_dict = recursive_dict_update(config_dict, env_config)

Do you know how to solve it? Thanks.

**Comment by hijkzzz** [comment]
I'm sorry I don't have a computer to test on windows, maybe you can debug it and provide a feedback, thanks
