### ISSUE TITLE
Question about GRF

### ISSUE THREAD

**Issue by BITminicc** [hijkzzz/pymarl2#14]
Hi, Awesome work! You extended GRF into the pymarl famework. However when I run it with vdn_gfootball.yaml, there is a lot of debugging information. Could you please help me to fix it?

Detail: absl Dump "episode_done": count limit reached / disabled

**Comment by hijkzzz** [comment]
Hello, these debug logs are printed by Google Football Environment and may need to refer to their documentation.

**Comment by BITminicc** [comment]
Thank you for your immediate reply. At present, it does not seem to affect the operation of the code. However, I do not know if there is any potential impact on the final result, which needs more verification.

**Comment by hijkzzz** [comment]
> 
These debug logs have no impact on performance. However, we did not use the CNN feature in the original  GRF paper, only the simple115 feature, which has a prominent impact on performance.
