### ISSUE TITLE
咨询两个问题

### ISSUE THREAD

**Issue by Bingoyww** [hijkzzz/pymarl2#16]
作者您好，我从‘starry...’那，被您评论来。之前一开始选择星际争霸开源代码，由于原版的注释太少，才选择'starry...'。
1.现在运行qmix，是都已经微调过的吗？
2.maps的由来，请问Q_plex里的类似7sz map是怎么来的？在下载星际争霸的网页上，没看到这个地图，您这里也有主动提供新地图。

**Comment by hijkzzz** [comment]
用SC2的编辑器自己可以创造地图
