### ISSUE TITLE
关于mac

### ISSUE THREAD

**Issue by Sud0x67** [hijkzzz/pymarl2#2]
您好，我是一名新手，代码阅读起来遇到一些困难。我看到说这个框架使用了mac架构，可不可以简单给我解释一下这里mac分别指什么啊？谢谢啦

**Comment by hijkzzz** [comment]
mac指的是控制器，作用是封装策略网络的动作选择、网络forward等操作。

**Comment by hijkzzz** [comment]
function call stack
main --> run --> [runner ( --> mac 收集样本) + learner( --> mac forward 策略)]

**Comment by Sud0x67** [comment]
明白了，非常感谢
