### ISSUE TITLE
关于QMIX-with-attention的问题

### ISSUE THREAD

**Issue by Fanniao727** [hijkzzz/pymarl2#21]
1.请问有这篇QMIX-with-attention的文章或者资料吗？

**Comment by Fanniao727** [comment]
2.
![1648548450(1)](https://user-images.githubusercontent.com/68955885/160588106-89998dfb-ece4-4eb3-8d7c-07cc8704564b.png)
atten_rnn中b,a,e代表着什么
b是batchsize
a是n_agents
e呢？

**Comment by hijkzzz** [comment]
e 代表 embeding，即每个agent的信息
