### ISSUE TITLE
Problem when modify maps

### ISSUE THREAD

**Issue by AlRodA92** [hijkzzz/pymarl2#22]
Hi,

I am doing some personal researchs, and I used one of your maps (**1o_10b_vs_1r.SC2Map**) due to the terrain design tha allow me some tasks. I have modified the maps regarding the type and number of agents but when I tried to change some terrain features the code gives me the following error

![Error](https://user-images.githubusercontent.com/83612075/162023350-334f08cb-d69c-4ee1-bd39-b96d1a23f332.png)

The only modifications I made are elevate some of the terrain so I do not change the size of the map.

Do you know the reason of this error?

Thanks!

**Comment by Nickydusk** [comment]
Looks like the same issue: https://github.com/deepmind/pysc2/issues/326
