### ISSUE TITLE
关于QMIX在5m_vs_6m上训练的问题

### ISSUE THREAD

**Issue by yuanyaaa** [hijkzzz/pymarl2#27]
你好，请问一下，如果直接采用QMIX(config=qmix.yaml)，在5m_vs_6m上训练，需要修改qmix.yaml的文件参数吗？我们采用仓库提供的版本直接在5m_vs_6m上训练。test_won_rate大概在0.2左右，但是论文中可以达到0.9，想请教一下是哪里的问题
![image](https://user-images.githubusercontent.com/49089811/196019472-6bffce1f-b257-4cbc-b300-b15c70f855d2.png)

**Comment by hijkzzz** [comment]
> 你好，请问一下，如果直接采用QMIX(config=qmix.yaml)，在5m_vs_6m上训练，需要修改qmix.yaml的文件参数吗？我们采用仓库提供的版本直接在5m_vs_6m上训练。test_won_rate大概在0.2左右，但是论文中可以达到0.9，想请教一下是哪里的问题 ![image](https://user-images.githubusercontent.com/49089811/196019472-6bffce1f-b257-4cbc-b300-b15c70f855d2.png)

我最近再跑一下 中间修改了一些版本没重新试过，但是放心好了 无数人重复过这个仓库的饰演了

**Comment by hijkzzz** [comment]
刚才跑了一下 qmix.yaml 5m_vs_6m

bash run.sh qmix sc2 5m_vs_6m "" 1 0 1

![image](https://user-images.githubusercontent.com/19810594/196664004-593261fa-6c6f-4981-95da-d1edc1db3ee4.png)

如果你喜欢收敛的更快可以用 

bash run.sh qmix_high_sample_efficiency.yaml sc2 5m_vs_6m "" 1 0 1

这是4进程的版本，时间上更慢但是从step来看收敛更快。

**Comment by hijkzzz** [comment]
另外就是检查一下安装环境

```
conda create -n pymarl python=3.8 -y
conda activate pymarl

bash install_dependecies.sh
bash install_sc2.sh
```

其他可能的问题 等我跑完再回复你，谢谢

**Comment by hijkzzz** [comment]
bash run.sh qmix_high_sample_efficiency.yaml sc2 5m_vs_6m "" 1 0 1

94W样本时的胜率~ 5m_vs_6m VDN才是效果最好的可以到 100%（需要调节一下 hidden_size）

```
battle_won_mean:           0.1786       ep_length_mean:           25.6071       epsilon:                   0.0500       grad_norm:                10.6138
loss_td:                   0.4314       q_taken_mean:              1.3570       return_mean:              10.9647       return_std:                4.4557
target_mean:               1.3101       td_error_abs:              0.4314       test_battle_won_mean:      0.7500       test_ep_length_mean:      28.6562
test_return_mean:         17.5389       test_return_std:           4.2925
``````
