### ISSUE TITLE
Set trained model as opponent?

### ISSUE THREAD

**Issue by linshi9658** [hijkzzz/pymarl2#29]
Hello,

Based on the state-of-the-art algorithm, the reality is that the winning rate is close to 1 in many maps. Is the author interested in further expanding the function of pymarl2 to realize the battle between two models obtained by different algorithms? I think this can break through the upper limit of the difficulty of SC2's built-in computer, so as to keep SMAC alive forever.

**Comment by hijkzzz** [comment]
Sounds interesting, I will try to add these features later when I have time~
