### ISSUE TITLE
关于SC2的版本问题

### ISSUE THREAD

**Issue by Zzhixihuanyu** [hijkzzz/pymarl2#31]
请问作者，可否同在2.4.6的版本环境中与本项目进行对比实验呢？，如果在这个版本环境中，是否有需要注意调整的参数？

**Comment by hijkzzz** [comment]
没有太多要调整的，一般来说大多数论文和本项目对比问题最多的点在于
用单线程 vs 多线程的样本效率，通常多线程是时间效率高而会降低样本效率

如果不考虑时间，倾向刷高 steps 的样本效率建议用 qmix_high_sample_efficiency.yaml
