### ISSUE TITLE
QMIX在corridor地图下胜率一直为0，且会出现非法ACTION错误

### ISSUE THREAD

**Issue by swordest** [hijkzzz/pymarl2#32]
使用qmix_high_sample_efficiency.yaml情况下在较难的corridor地图下，test_battle_won_mean一直为0（实际上qmix.yaml也一样）。请教下那个地方可能出了问题，附上了完整的输出文件。

另外还有个比较随机的问题，某几次实验室的时候，会出现action不合法导致的assertion错误，导致程序直接退出（如下面的cout所示），不知道这个问题是否有解决方案？

盼回复。谢谢！

[INFO 10:16:50] my_main t_env: 3086524 / 10050000
[INFO 10:16:50] my_main Estimated time left: 22 hours, 38 minutes, 44 seconds. Time passed: 6 hours, 22 minutes, 13 seconds
[INFO 10:16:58] my_main Recent Stats | t_env:    3086524 | Episode:    81500
battle_won_mean:           0.0000	ep_length_mean:           42.6525	epsilon:                   0.0500	grad_norm:                 0.2738
loss_td:                   0.0163	q_taken_mean:              0.6618	return_mean:               9.7562	return_std:                1.3360
target_mean:               0.6574	td_error_abs:              0.0163	test_battle_won_mean:      0.0000	test_ep_length_mean:      43.0625
test_return_mean:         10.0525	test_return_std:           1.6540	
[INFO 10:17:52] my_main Updated target network
Process Process-2:
Traceback (most recent call last):
  File "/home/ts1-guest/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ts1-guest/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ts1-guest/RL_study/pymarl2/src/runners/parallel_runner.py", line 233, in env_worker
    reward, terminated, env_info = env.step(actions)
  File "/home/ts1-guest/RL_study/pymarl2/src/envs/starcraft/StarCraft2Env.py", line 406, in step
    sc_action = self.get_agent_action(a_id, action)
  File "/home/ts1-guest/RL_study/pymarl2/src/envs/starcraft/StarCraft2Env.py", line 477, in get_agent_action
    assert avail_actions[action] == 1, \
AssertionError: Agent 1 cannot perform action 14
CloseHandler: 127.0.0.1:54100 disconnected
[cout.txt](https://github.com/hijkzzz/pymarl2/files/11132228/cout.txt)

**Comment by hijkzzz** [comment]
请问可以帮我 回到前面的 commit  比如 
0943850313495a80c133c45a021c24b473629d3e
测试一下吗？如果你的问题一直存在，可能是我后面修改了某些代码而没有充分测试。

**Comment by hijkzzz** [comment]
我已经重新跑了这张图，可以复现效果。所以问题出在smac版本或者SC版本上，你可以排查一下。

**Comment by swordest** [comment]
感谢详细回复。我用的是SC2.4.10 + PyTorch 1.12.1，这两天测试下把smac版本回退一下，看看效果如何
