### ISSUE TITLE
Reference at 'refs/heads/master' does not exist

### ISSUE THREAD

**Issue by lihaibineric** [hijkzzz/pymarl2#37]

**Comment by lihaibineric** [comment]
when i run pymarl2 i met this error: 


raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist


can you help me?

**Comment by lihaibineric** [comment]
pip install sacred==0.7.5
Just reduce the version of the python library, all will be ok.

**Comment by hijkzzz** [comment]
thx
