### ISSUE TITLE
关于test_won_rates

### ISSUE THREAD

**Issue by Sud0x67** [hijkzzz/pymarl2#4]
您好，有一个小问题请教您，test_won_rates 为什么对应的时间步每次都不一样呢，如果这样画图的时候应该怎么处理呢？

**Comment by hijkzzz** [comment]
对齐到某一个steps 比如 10000 20000

**Comment by Sud0x67** [comment]
那边上的阴影线不应该是求当前时间步的均值和最大值最小值画出来的吗？ 比如192步，只有一个值如何画阴影线呢
