### ISSUE TITLE
TensorBoard logger not working

### ISSUE THREAD

**Issue by kjyeung** [hijkzzz/pymarl2#5]
Hi, thanks for the good work! I installed the dependencies as instructed and successfully started training. However, it seams that the tensorboard logs are not written to /result directory although I set the use_tensorboard param to "true" in src/config/default.yaml. Could you please help me with this?

**Comment by hijkzzz** [comment]
As shown in src/run/run.py line 46:

```
        tb_logs_direc = os.path.join(dirname(dirname(abspath(__file__))), "results", "tb_logs")
```

So the logs are in /src/run/results/tb_logs
Thanks~

**Comment by kjyeung** [comment]
> As shown in src/run/run.py line 46:
> 
> ```
>         tb_logs_direc = os.path.join(dirname(dirname(abspath(__file__))), "results", "tb_logs")
> ```
> 
> So the logs are in src/run/results/tb_logs
> Thanks~

My fault. Thanks for your reply!
