### ISSUE TITLE
Why use NRNNAgent and NMAC?

### ISSUE THREAD

**Issue by kjyeung** [hijkzzz/pymarl2#8]
Hi, I've been reading through the code and found that the NRNNAgent(from n_rnn_agent.py) has almost negligible differences from the RNNAgent(from rnn_agent.py). The same goes between the BasicMAC(basis_controller.py) and the NMAC(n_controller.py).
It could be my carelessness. Could you kindly explain the reasons behind this design? What does the "n" in the names(as in n_controller.py) stand for?
Thank you in advance!

**Comment by hijkzzz** [comment]
...next qmix
yes, they are the same.
